project:
  type: website
  output-dir: docs  
  pre-render: 
    - clean_webr.R
  
extensions:
  - quarto-ext/shinylive

website:
  title: "Cobb County Fire & Emergency Services"
  navbar:
    logo: resources/images/CCFES-Logo-Small.png
    left:
      - href: index.qmd
        text: Introduction
      - href: area_characteristics.qmd
        text: Area Characteristics
      - href: programs_and_services.qmd
        text: Programs and Services
      - href: test_dash.qmd
        text: Test Dashboard

format:
  html:
    code-fold: false
    code-tools: false
    page-layout: full
    include-after-body: footer.html
    filters: 
      - shinylive
    embed-resources: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    #resources: 
    #  - sw.js
    grid:
      body-width: 1200px
      

execute: 
  echo: false
  warning: false
  message: false
  error: false
  include: true

