project:
  type: website
  output-dir: docs  
  
extensions:
  - quarto-ext/shinylive

website:
  title: "Cobb County Fire & Emergency Services - CRA SOC"
  navbar:
    logo: resources/images/CCFES-Logo-Small.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    filters: 
      - shinylive
    embed-resources: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



